### ISSUE TITLE
Great paper - had a question but there's no discussions on this repo

### ISSUE THREAD

**Issue by elliot-hicks** [bfly123/PINN_WE#1]
Dear @bfly123 and others,

I read your paper and found it extremely useful - thank you for sharing this work openly! I had a few questions if you don't mind my asking - you dont have a discussion board so I hope you don't mind me creating an Issue to ask. No problems if you are not answering questions at this time.

* I noticed when sampling collocation points you dont sample from space randomly, but instead sample from a mesh grid. Why did you choose to do this? Do you have any rules to create appropriate fineness in meshes?  

* I've reproduced your results using another framework [(DeepXDE)](https://github.com/lululxvi/deepxde/blob/master/docs/modules/deepxde.rst) and varied the value of $\epsilon_{2}$ and saw a lot of changes from one value to another, do you have any tips on selecting the correct value?

* I would have thought we'd have to disconnect the compression weighting factor ( $\lambda$ ) from the graph so that the model doesnt simply reduce $\lambda$ to zero (and hence the residuals to zero), but you do not, is there a reason why it works?

* How would PINN-WE handle source terms, would they also be multiplied by $\lambda$? 

Your paper was great, thanks again!

**Comment by SeemSeam** [comment]
Hello @elliot-hicks ,
Thank you for your questions. I will try my best to answer you. If I can not explain clearly, we can discuss more.
- First, for PINNs, totally random is better than sampling from a mesh as higher randomness will lead to higher utilization of the collections.  But when we compare the result with traditional methods such as FDM or FVM, with same mesh nodes will have a good contract with those methods.  Especially in low-dimensional problems. However, for high-dimensional problems, sampling from mesh is inefficient.  

- Second question:  In Burgers problem, I have tried $\varepsilon_2$ as 0.05, 0.1, and 0.2. They all can improve the solution compared to the original PINNs. But I don't know how to decide $\varepsilon_2$ we can get the best result.  Also, the randomness of the result as your test may not only be caused by $\varepsilon_2$, your can try to change another hyperparameter, even a random seed, and you may get a very different result. I guess this is due to the instability or underdetermined of the NN in fitting a discontinuous solution. 

- Third question：I don't very understand how to disconnect $\lambda$ away from the graph. But I do want $\lambda$ to reduce to zero when the strong discontinuity forms, as NN cannot bear a large gradient if the transition point is inside a discontinuous region, and it will carry a large function loss of cause, blocking the training.  I want to reduce its influence and move the transition point out into smooth regions by $\lambda$ , and then we can get a real discontinuous solution.  

- The last one： I think the WE method benefits the problems with shock wave formation, whether in pure hyperbolic equations or with source terms. It can let your training quickly converge to a discontinuous solution. 

Thank you for your questions. No matter the instability or uniqueness, all are essential and opening questions in PINNs.  We may do a lot of work here.

**Comment by elliot-hicks** [comment]
Hi @bfly123 , Thanks so much for your responses, they clear everything up for me. I've re-read your paper a few times now and had a couple of successes with the PINN-WE method in alternative applications! Thanks for the great paper and even more so for open-sourcing the code 😄

**Comment by elliot-hicks** [comment]
I will close the issue, but am really interested in your future works and will keep track of this space.
